### PR TITLE
fix: better navigator.webdriver faking

### LINKED ISSUE #13: Needlessly sets navigator.webdriver to undefined instead of leaving it as-is
Sometime last year, Chrome devs changed it so that the default state of `navigator.webdriver` is `false`, instead of `undefined`.
Therefore, the webdriver evasion, ironically, makes it easier to spot the headless browser.

### PR DESCRIPTION
**Pull request by Mattwmaster58**
fixes #13

### CODE REVIEW

**Comment by hamzaydia** [comment]
why this is not merged?

**Comment by milahu** [comment]
fails on [selenium-detector](https://hmaker.github.io/selenium-detector/) with `detected`
because the [hasConstructorAlias test](https://github.com/HMaker/HMaker.github.io/blob/3bd8c05c78e24571ed8fa056733d5ae1345b6910/selenium-detector/chromedriver.js#L106) fails on `window.Array`

fails on cloudflare with `playwright._impl._api_types.Error: net::ERR_ABORTED`
but this could be a different issue

the linked [stackoverflow answer](https://stackoverflow.com/a/69533548) shows different code, but that also fails on selenium-detector

```diff
- Object.defineProperty(Object.getPrototypeOf(navigator), 'webdriver', {
+ Object.defineProperty(Navigator.prototype, 'webdriver', {
```


```py
with (
    playwright.sync_api.sync_playwright() as pw,
):
    browser = pw.chromium.launch()
    page = browser.new_page()
    playwright_stealth.stealth_sync(page)
    # NOTE changes take effect only on the first page.goto
    page.goto("https://google.de/") # TODO localhost server
    assert page.evaluate("navigator.webdriver") == False
    js = "Object.getOwnPropertyDescriptor(Navigator.prototype, 'webdriver').get.toString()"
    # this fails. actual value: function () { [native code] }
    assert page.evaluate(js) == "function get webdriver() { [native code] }"
```

it should be easier to [pass](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch) `--disable-blink-features=AutomationControlled` to chrome, but this has no effect, and also fails on selenium-detector

```py
with (
    playwright.sync_api.sync_playwright() as pw,
):
    browser = pw.chromium.launch(
        args=[
            # none of these are working
            "--disable-blink-features",
            "--disable-blink-features=AutomationControlled",
            "--enable-automation=False",
        ],
    )
```

**Comment by awtkns** [comment]
Hey @AtuboDad can this feature get released? :) Seems its not in the latest pypi version

**Comment by KrAsH-CoD3** [comment]
Hey @AtuboDad, a subtle reminder the pypi version is not up to date with this repo.

**Pull request merged**
